name: avgleclient
description: Avgle Client Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

  # For Analyzer
  pedantic: ^1.9.0

  cupertino_icons: ^0.1.3

  # For Architecture
  flutter_hooks: ^0.12.0
  hooks_riverpod: ^0.6.1

  # For Networking
  dio: ^3.0.9
  dio_http_cache: ^0.2.8
  retrofit: ^1.3.4
  logger: any

  # For UIs
  lottie: ^0.5.1
  shimmer: ^1.1.1

  # For Model
  json_serializable: ^3.3.0

  # For DateTime
  intl: ^0.16.1

  # For Webview
  webview_flutter: ^0.3.22+1

  # For Firebase
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3

  # For Local DB
  sqflite: ^1.3.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  retrofit_generator: ^1.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/